[package]
name = "guessing-game"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
owo-colors = "3"
clap = "4.0.32"
